# Generated by Django 5.2.3 on 2025-06-25 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0007_labor_register_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor_register',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
